language: java
jdk: openjdk11
script: true
after_success:
- mvn clean test
- mvn jacoco:report
- mvn coveralls:report -DrepoToken="${COVERALLS_TOKEN}"
env:
  global:
    secure: eOgJlmFuKMlVjr7hgysQC3bNcuBWSPE0Wx4Qwo7ZcciSWZDuFf1NCXbrsp0krizuSuxcau4ZR3ECPVscS9bfC/KvZ0jrRrvU9sTnjgOUkOeoNc7638dU28IknbjtV4zCW6CHfmxmWor3UgqeFtTTSKqZ3LpLtsucPC5WrTRvM8OK23APc4qECuu+oV7rcnyCkG2WOv6C74zwHtVy5Ig0QvWdtIBKfS/UlSRL7UiWjoCADE+vpqjKl15sWKgkv7ZlQmX3UDLhh5u6kBZyEJYvYIaBmQFv8knu42/9MPIpOD0m+bkaHWTJly6XbtMA77shdI3cvoqIoH95tidPnpv5KUv/8YU1st4rBw6nn0b707YHLee6ymJ3uIbQZHzdcUNHbfE0BUZT5ljc3I4G4icF0f5xobbgODOqfPKmugahcmTr/0xtppP8N2rvlBOt2EySmZg1sXhbVCfoYqC8w3FIlgpnhSn7SxcnMQHAwEaJ5oRpvp/Cn5uCZYOpH8RAQ9FMhty85fX1FTY0iZn3ugyrW/o61haWzKTVvCjSJ516QV9mTmUedTYrWd65hxx+JRIB/9gzqzWPeP3Tzwl7LmEBjFO1HAWSJtMCrzJO7W/6Nms8gx7NkQcUnxS8wO2wAKzQjYb7Uit+Ez2eGjEty/ZJnvjTE75Nk2RUad6TWmjE/nE=
